In [3]:
import pandas as pd
data = pd.read_csv('iBeacon_RSSI_Labeled.csv')
data=data.dropna(how="all")
data=data.drop(['date'],axis=1)
# display the first 5 rows
data.head(12)

location  b3001  b3002  b3003  b3004  b3005  b3006  b3007  b3008  b3009  \
0       O02   -200   -200   -200   -200   -200    -78   -200   -200   -200   
1       P01   -200   -200   -200   -200   -200    -78   -200   -200   -200   
2       P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   
3       P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   
4       P01   -200   -200   -200   -200   -200    -77   -200   -200   -200   
5       P01   -200   -200    -82   -200   -200   -200   -200   -200   -200   
6       P01   -200   -200    -80   -200   -200    -77   -200   -200   -200   
7       P02   -200   -200    -86   -200   -200   -200   -200   -200   -200   
8       R01   -200   -200   -200    -75   -200   -200   -200   -200   -200   
9       R01   -200   -200   -200    -75   -200   -200   -200   -200   -200   
10      R01   -200   -200   -200    -80   -200   -200   -200   -200   -200   
11      R01   -200   -200   -200    -78   -200   -200   -200   -200   -200   

    b3010  b3011  b3012  b3013  
0    -200   -200   -200   -200  
1    -200   -200   -200   -200  
2    -200   -200   -200   -200  
3    -200   -200   -200   -200  
4    -200   -200   -200   -200  
5    -200   -200   -200   -200  
6    -200   -200   -200   -200  
7    -200   -200   -200   -200  
8    -200   -200   -200   -200  
9    -200   -200   -200   -200  
10   -200   -200   -200   -200  
11   -200   -200   -200   -200

In [4]:
datamat=data.values

In [9]:
datamat[1,1:]

array([-200, -200, -200, -200, -200, -78, -200, -200, -200, -200, -200,
       -200, -200], dtype=object)

In [11]:
datamat[:,1:]

array([[-200, -200, -200, ..., -200, -200, -200],
       [-200, -200, -200, ..., -200, -200, -200],
       [-200, -200, -200, ..., -200, -200, -200],
       ...,
       [-200, -67, -200, ..., -200, -200, -200],
       [-200, -79, -200, ..., -200, -200, -200],
       [-200, -75, -200, ..., -200, -200, -200]], dtype=object)

In [12]:
datamat[:,0]

array(['O02', 'P01', 'P01', ..., 'I01', 'I01', 'I01'], dtype=object)

In [38]:
from sklearn.svm import SVC
import numpy as np
X= np.array(datamat[:,1:])
y = np.array(datamat[:,0])
 
clf = SVC()
clf.fit(X,y)
# np.shape(X)
print (clf.fit(X,y))
print (clf.predict(X))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
['P01' 'P01' 'P01' ... 'J04' 'K03' 'K05']


In [36]:
datamat[0,1:]

array([-200, -200, -200, -200, -200, -78, -200, -200, -200, -200, -200,
       -200, -200], dtype=object)

In [46]:
from sklearn import metrics
metrics.accuracy_score(clf.predict(X),y)

0.4852112676056338

In [47]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)
print (clf.predict(X))
print(clf.predict_proba(X))#预计在每个类的概率
metrics.accuracy_score(clf.predict(X),y)

['P01' 'P01' 'P01' ... 'J04' 'K03' 'I01']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


0.5802816901408451

In [51]:
from sklearn import ensemble
clf=ensemble.RandomForestClassifier()
clf = clf.fit(X, y)
print (clf.predict(X))
#print(clf.predict_proba(X))#预计在每个类的概率
metrics.accuracy_score(clf.predict(X),y)

['P01' 'P01' 'P01' ... 'J04' 'K03' 'M04']


0.569718309859155